name: PyTest

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:  
  pytest:
    name: Functional/Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python -m pytest